### ISSUE TITLE
Why not run bitcoind as root?

### ISSUE THREAD

**Issue by levino** [ExodusMovement/docker-bitcoind#1]
Why create a user? This will only make troubles (e.g. you link a folder from the host into the container, then the `bitcoind` might not be able to write to it.)

**Comment by fanatid** [comment]
Hey @Levino :clap: happy to hear words from you.

Yes, there can be some problems with permissions for database, but all they can be solved. Nobody run `bitcoind` on host machine from root user, why we should run anything from root while container is not fully isolated?
Awesome article with explanation https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b
At the end, uid/gid can be changed on running container.
