### ISSUE TITLE
Dont ship build tools with final image.

### ISSUE THREAD

**Issue by levino** [ExodusMovement/docker-bitcoind#2]
Currently the build tools are in the same image as the executable `bitcoind`. There is a nice paradigm (kinda new) from docker called [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/#before-multi-stage-builds). I recommend using it to improve this image.

**Comment by fanatid** [comment]
I did not knew about multi-stage builds, thank you!

Build tools actually removed at then end of big RUN command ;)
https://github.com/ExodusMovement/docker-bitcoind/blob/7fac9a2e10e21f12b6d7ab99ca9ed849922d2bb0/Dockerfile#L41-L42

**Comment by fanatid** [comment]
@Levino thank you that bring this concept, we switched to multi-stage.
